options:
  merge-default-rules: true
  max-warnings: 10
rules:
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedbem'
  indentation: 0
  no-css-comments: 0
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
  property-sort-order:
    - 1
    -
      order: 'smacss'

