<!--[if lt IE 9]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

  <script src="/jspm_packages/system.js"></script>
  <script src="/config.js"></script>
  <script>
    System.import('/assets/js/main.js');
  </script>
